//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [Key]
        public int id_book { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> id_publisher { get; set; }
        public Nullable<int> id_author { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
