//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CourseTable
    {
        [Key]
        public int Id { get; set; }
        [ForeignKey("DISCIPLINE")]
        public int idDiscipline { get; set; }
        [ForeignKey("Student")]
        public int idStudent { get; set; }
        public string Name { get; set; }
        public string Lector { get; set; }
        public string Surname { get; set; }
    
        public virtual DISCIPLINE DISCIPLINE { get; set; }
        public virtual Student Student { get; set; }
    }
}
